version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GROUP_CHAT_ID=${GROUP_CHAT_ID}
    volumes:
      - .:/app
    restart: unless-stopped